name: crowdapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  icons_flutter: ^0.0.4
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.1.0
  mapbox_maps_flutter: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Geist
      fonts:
        - asset: fonts/Geist-Regular.ttf
        - asset: fonts/Geist-Black.ttf
        - asset: fonts/Geist-Light.ttf
        - asset: fonts/Geist-Bold.ttf
        - asset: fonts/Geist-Medium.ttf
        - asset: fonts/Geist-SemiBold.ttf
        - asset: fonts/Geist-Thin.ttf
        - asset: fonts/Geist-UltraBlack.ttf
        - asset: fonts/Geist-UltraLight.ttf
